# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ISLBox
                                 A QGIS plugin
 Boîte à outils pour tout ISLien
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-03-10
        copyright            : (C) 2021 by ISL
        email                : godet@isl.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "ISL"
__date__ = "2021-03-10"
__copyright__ = "(C) 2021 by ISL"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name,unused-argument
    """Load ISLBox class from file ISLBox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .isl_box import ISLBoxPlugin

    return ISLBoxPlugin()
