.\osgeo4w-setup.exe `
  --menu-name "QGIS ISL" `
  --root "C:\OSGeo4W" `
  --advanced  `
  --quiet-mode   `
  --local-install `
  --local-package-dir "\\islsudouest\users\Godet\Qgis\DEPLOY\http%3a%2f%2fwww.norbit.de%2fosgeo4w%2fv2%2f" `
  --autoaccept  `
  --delete-orphans `
  --upgrade-also `
  -C Libs `
  -C Desktop `
  -C Commandline_Utilities